BEGIN;

ALTER TABLE em
ADD COLUMN employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY;

DO $$
DECLARE
    primary_key_name text;
BEGIN
    SELECT tc.constraint_name
    INTO primary_key_name
    FROM information_schema.table_constraints tc
    WHERE tc.table_name = 'em'
      AND tc.constraint_type = 'PRIMARY KEY';

    IF primary_key_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE em DROP CONSTRAINT %I', primary_key_name);
    END IF;
END $$;

ALTER TABLE em
ADD CONSTRAINT em_pkey PRIMARY KEY (employee_id);

COMMIT;
