<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>

        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="1.4.0" />
        <PackageReference Include="nunit" Version="3.12.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ShipIt\ShipIt.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <Content Update="App.config">
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
        <None Remove=".env" />
        <Content Include=".env">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
